FROM canelrom1/apache-php7:latest

ENV CA_PROVIDENCE_VERSION=1.7.6

RUN apk add curl \
            #exiftool \
            #ffmpeg \
            #ghostscript \
            #graphicsmagick \
            #graphicsmagick-dev \
            #imagemagick \
            #libgd \
            #libraw \
            mariadb-client \
            #mediainfo \
            php7-ctype \
            php7-curl \
            php7-exif \
            php7-iconv \
            php7-json \
            php7-mbstring \
            php7-mcrypt \
            php7-memcached \
            php7-openssl \
            php7-phar \
            php7-posix \
            php7-simplexml \
            php7-xml \
            php7-xmlreader \
            php7-xmlwriter \
            php7-zip \
            #poppler-utils

RUN rm -rf /var/www/html \
 && curl -SsL https://github.com/collectiveaccess/providence/archive/$CA_PROVIDENCE_VERSION.tar.gz | tar -C /var/www/ -xzf - \
 && mv /var/www/providence-$CA_PROVIDENCE_VERSION /var/www/html \
 && cp /var/www/html/setup.php-dist /var/www/html/setup.php

RUN chown -R apache:apache /var/www/html

COPY entrypoint.sh /entrypoint.sh
RUN chmod 777 /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

CMD ["apache2"]

# vim: tw=200
